runtime: java8
service: 'default'
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
api_version: '1.0'
handlers:
- url: /.*
  script: unused
  login: optional
  secure: optional

skip_files: app.yaml
